POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5sb2MiLCJleHAiOjE3MzQ5ODUzNTUsInVzZXJJZCI6MX0.PEVV12Rt8Iin1N9ddH9bpY8OR2_xJjdr7s00SwyEl7w

{
  "name": "Test event New 5",
  "description": "Test event",
  "location": "A test location ",
  "dateTime": "2024-01-01T15:30:00.000Z"
}
