DELETE http://localhost:8080/events/
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQG1haWwubG9jIiwiZXhwIjoxNzM0OTgxODQxLCJ1c2VySWQiOjJ9.yU_TIzs-56SAEtup0XRFeT7eFrtDgTERAQylcbMb9wU
