PUT http://localhost:8080/events/2
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQG1haWwubG9jIiwiZXhwIjoxNzM0OTgxNTUyLCJ1c2VySWQiOjJ9.7dr8HfFo95r08JUiOc3ZNNFgRcfpkfFlCHMpC1WsZv8

{
  "name": "Updated event again",
  "description": "Another Test event",
  "location": "A test location (Updated!)",
  "dateTime": "2024-01-01T15:30:00.000Z"
}
